### ISSUE TITLE
Could you fix this issue

### ISSUE THREAD

**Issue by crunkazcanbe** [xbony2/Advanced-Power-Management-2#1]
I am using your version you updated not long ago for 1.7.10 and in the console I see http://pastebin.com/NcTEJHWh

I know its no big deal , but it seems to ping my internet alot causing a bit of lag with me and my wife playing in lan mode .

If you don't I understand its just abit of spam in the console .

Thank you!

-Crunk

**Comment by xbony2** [comment]
Not an Advanced Power Management bug :P nuclear control bug. It's mostly just some console spam, but I'll see if I can optimize Jadar's old code.

**Comment by crunkazcanbe** [comment]
Sorry I put it in the wrong spot .

I know this is not the place for this , but do you have plans on keeping this updated , and possibly adding new features to this old mod ? Like NC2 mod this was one of my old FAVS.

Thank you man!

-Crunk

**Comment by xbony2** [comment]
Not really :/ I'd like to pass this mod onto another more interested mod author if I can.
